[package]
name = "libssh-sys"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[features]

vendored-libssh0104 = []

[dependencies]

[dev-dependencies]

[build-dependencies]
cmake = "0.1.48"
bindgen = "0.69.1"
