[package]
name = "wolfssl"
version = "0.1.0"
edition = "2021"

[features]

wolfssl430 = []

[dependencies]
wolfssl-sys = { path = "../wolfssl-sys" }

libc = { version = "0.2.126" }
foreign-types = { version = "0.5.0" }
bitflags = { version = "1.3.2" }

log = "0.4.17"
