name: Deploy documentation

on:
  workflow_call:

jobs:
  deploy-docs:
    name: deploy docs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: download api-docs
        uses: actions/download-artifact@v4
        with:
          name: docs-api
          path: artifacts/api
      - name: download book
        uses: actions/download-artifact@v4
        with:
          name: docs-book
          path: artifacts/book
      - name: deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: artifacts
